### ISSUE TITLE
Issue with Histogram for Recursive QAOA

### ISSUE THREAD

**Issue by deepquantum88** [Qiskit/qiskit-optimization#101]
### Information

- **Qiskit Aqua version**: 0.8.0
- **Python version**: 3.8.5
- **Operating system**:  Windows 10, 64bit

### What is the current behavior?
spsa = SPSA(maxiter=250)
backend = Aer.get_backend('qasm_simulator')
qaoa_mes = QAOA(optimizer=spsa, quantum_instance=backend)
qaoa = MinimumEigenOptimizer(qaoa_mes)
#result = qaoa.solve(qp)
cutoff = 3
rqaoa_solver = RecursiveMinimumEigenOptimizer(min_eigen_optimizer=qaoa, min_num_vars=cutoff,min_num_vars_optimizer=exact)
result2 = rqaoa_solver.solve(qp)
print(result2)

### Steps to reproduce the problem
plot_histogram(result.min_eigen_solver_result.eigenstate, bar_labels=False)

### What is the expected behavior?
It does not show a histogram for rqaoa

### Suggested solutions

How can we plot the histogram for rqaoa algorithm also after solving the qubo problem. Because recursive eigensolver does not support histogram attribute

**Comment by deepquantum88** [comment]
On using OptimizationResult.samples for qaoa, it lists all the sample solutions. But with rqaoa, lists only optimal one as below

[SolutionSample(x=array([1., 0., 1., 0.]), fval=-4.0, probability=1.0, status=<OptimizationResultStatus.SUCCESS: 0>)]

How can I get all solution samples from RQAOA?

**Comment by t-imamichi** [comment]
`[SolutionSample(x=array([1., 0., 1., 0.]), fval=-4.0, probability=1.0, status=<OptimizationResultStatus.SUCCESS: 0>)]` is the solution sample. Because the probability is 1, there is only 1 sample. It's correct.

**Comment by adekusar-drl** [comment]
Hello,

First of all, please consider moving to qiskit-optimization (https://github.com/Qiskit/qiskit-optimization/) instead of aqua. Aqua is deprecated since the release 0.9.

Then, next time please provide a snippet that can be run and examined. The example above can not be just executed and the issue can't be easily verified.

And the most important part. There is an additional parameter `history` in the `RecoursiveMinimumEigenOptimizer` constructor. Possible values are: `IntermediateResult.NO_ITERATIONS`, `IntermediateResult.LAST_ITERATION`, `IntermediateResult.ALL_ITERATIONS`. Last two options populate `history` property of the corresponding result instance. Depending on the value of the `history` in the constructor, the `history` property of the `RecoursiveMinimumEigenOptimizationResult` contains a tuple of `List[MinimumEigenOptimizationResult]` and `OptimizationResult`. The list, in turns, contains all (or just last) intermediate result objects obtained in iterations. The second value in the tuple is an instance of `OptimizationResult` obtained at the last iteration. So, you can explore what you get in the history and plot a histogram. Of course, this only works if the underlying optimizer provides this additional information and this information is "good enough" for plotting, this may not be the case in the recursive optimization since variables are eliminated in the iterative process and you don't get `samples` in the same fashion as in `MinimumEigenOptimizer` at each iteration. Long story short: @t-imamichi is right, you get a correct sample (which is a degenerate case of multiple samples) at the last iteration.

Please take a look at the documentation:
https://qiskit.org/documentation/optimization/stubs/qiskit_optimization.algorithms.RecursiveMinimumEigenOptimizer.html

**Comment by adekusar-drl** [comment]
@deepquantum88 I'm closing the issue for now. If you still have questions, you can post them here and we can re-open the issue.
