### ISSUE TITLE
Make docplex optional

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#159]
### What is the expected enhancement?

Once we support model translators, some users don't want to use docplex as dependent.
So, I would like to investigate how we can make `QuadraticProgram` works without docplex.

**Comment by woodsp-ibm** [comment]
Is there a given reason why users don't want it as a dependent - if its used by QP internally what does it matter? It is simply installed by pip as a dependent and is under Apache license; what is the rationale of more optionality here? In the past for big/complex packages it has been disk/memory space since some want to run in more limited envs e.g. small containers - sometimes it has been licensing related.

**Comment by t-imamichi** [comment]
This is a request from @stefan-woerner. He mentioned that Gurobi users might not want to install docplex.
