### ISSUE TITLE
Callback for example in readme

### ISSUE THREAD

**Issue by saum-g** [Qiskit/qiskit-optimization#171]
I added a callback to the QAOA constructor in the example in the README. The callback appends the mean value to a list and later I plot a graph of those values. Instead of the mean cost increasing with iteration number, it seems to be decreasing in the graph obtained. Is this some issue with the callback or something else?

**Comment by woodsp-ibm** [comment]
Although the problem is created for maximize you can see it uses a MinimumEigenOptimizer to solve it. If you look into the code of MinimumEigenOptimizer you will find it runs convertors to turn the problem into something it can solve - as part of this it will convert it to a minimization problem (see code snippets below). This is why you see the values decreasing. In the end there is an interpret method that will intepret the result it gets in the context of the original problem, so you see the solution to your problem not the converted one which was solved. Hope that helps explain.


https://github.com/Qiskit/qiskit-optimization/blob/7f1ec648cee9c6baffa9354df08e116eef5dce58/qiskit_optimization/algorithms/minimum_eigen_optimizer.py#L149

https://github.com/Qiskit/qiskit-optimization/blob/7f1ec648cee9c6baffa9354df08e116eef5dce58/qiskit_optimization/algorithms/optimization_algorithm.py#L365-L386

https://github.com/Qiskit/qiskit-optimization/blob/7f1ec648cee9c6baffa9354df08e116eef5dce58/qiskit_optimization/converters/quadratic_program_to_qubo.py#L36-L51

**Comment by saum-g** [comment]
Thanks a lot for your explanation, particularly for the pointers to code. That clarifies my confusion
