### ISSUE TITLE
qiskit.opflow and qiskit.exceptions.MissingOptionalLibraryError are not available

### ISSUE THREAD

**Issue by RichardOberdieck** [Qiskit/qiskit-optimization#38]
### Information

- **Qiskit Optimization version**: latest (based on commit 57b59c6)
- **Python version**: 3.7.6
- **Operating system**: Linux, macOS

### What is the current behavior?
I have [forked the project](https://github.com/RichardOberdieck/qiskit-optimization) to add a connector to `gurobipy` in `quadratic_program.py` and `max_cut.py`.

When I want to run the tests though, I get an `ImportError` for the following two items (at least):

- `qiskit.opflow` (e.g. in line 45 of `quadratic_program.py`)
- `MissingOptionalLibraryError` from `qiskit.exceptions` (e.g. line 44 of `quadratic_program.py`)

### Steps to reproduce the problem

1. Open a clean shell (e.g. using `docker run -it continuumio/miniconda3:latest`)
2. Run:

```
conda install pip
pip install qiskit
```

3. Try to run `import qiskit.opflow` or `from qiskit.exceptions import MissingOptionalLibraryError`.

### What is the expected behavior?
This should not fail.

### Suggested solutions
I cloned the `qiskit` project as well, but I don't see where the issue is. Note that `qiskit-optimization` requires `qiskit-terra>=0.17.0` as per the `requirements.txt`, but according to the [qiskit-terra](https://github.com/Qiskit/qiskit-terra) page, they are only at release 0.16.4 at the moment.

**Comment by manoelmarques** [comment]
Qiskit optimization is where the optimization code will reside instead of qiskit-aqua. However it hasn’t been released yet and qiskit-aqua is still functional in Pypi. The documentation points to the current releases and if you install from Pypi, you will get a qiskit-terra incompatible with qiskit-optimization. In order to contribute to this new repo, you need to clone qiskit-terra from master which has the required version 0.17.0

**Comment by manoelmarques** [comment]
The master versions of the application repos are always in synch with the master versions of terra, ignis, aer. So in general, when developing, it is best to have the cloned master versions of those repos installed instead of the released ones. This is explained at CONTRIBUTING.md, section ‘Installing Qiskit Optimization from source’

**Comment by RichardOberdieck** [comment]
Thanks, my mistake. Got it working and will submit my PR in the coming days.
