### ISSUE TITLE
Test requirements need to be listed in setup.py

### ISSUE THREAD

**Issue by yurivict** [Qiskit/qiskit-optimization#403]
### Environment

- **Qiskit Optimization version**: 750c2c8
- **Python version**: 3.9
- **Operating system**: FreeBSD 13.1

In the FreeBSD port I need to fill the TEST_DEPENDS clause and it isn't clear what is a complete set of test dependencies.

### What is happening?

n/a

### How can we reproduce the issue?

n/a

### What should happen?

n/a

### Any suggestions?

n/a

**Comment by mtreinish** [comment]
I'm closing this for the same reason as Qiskit/qiskit-terra#8498 the `requirement-dev.txt` list includes all the test only requirements. If you need a list of test dependencies for FreeBSD packaging I would just use that.

**Comment by yurivict** [comment]
```requirement-dev.txt``` contains items irrelevant for testing.

**Comment by yurivict** [comment]
setup.py has a dedicated variable ```tests_require``` just for this purpose.
If ```dev_require``` would have been sufficient, ```tests_require``` wouldn't have been defined.

**Comment by mtreinish** [comment]
All the test specifiers in setuptools, including `tests_require` have been deprecated for almost 3 years now and they're not recommend for use because they will be removed in a future release (https://setuptools.pypa.io/en/latest/references/keywords.html). They were only ever used by setuptools if you configure your setup.py to run tests (which we don't as that is quite a limited interface and deprecated).
