### ISSUE TITLE
Maximize to minimize converter

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-optimization#41]
### What is the expected enhancement?

Some algorithms convert maximization problems into minimization problems internally. By introducing `MaximizeToMinimize` converter, we can simplify the codes of the algorithms by adding `MaximizeToMinimize` to the default converter list.

https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/cobyla_optimizer.py#L115
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/minimum_eigen_optimizer.py#L198
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/minimum_eigen_optimizer.py#L244
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/multistart_optimizer.py#L87
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/slsqp_optimizer.py#L174
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/warm_start_qaoa_optimizer.py#L322
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/grover_optimizer.py#L163
https://github.com/Qiskit/qiskit-optimization/blob/57b59c64bf0ba72057465f2a6ff3560b26239ced/qiskit_optimization/algorithms/admm_optimizer.py#L403

**Comment by tomtuamnuq** [comment]
Hello @t-imamichi. I am following Qiskit for a while now and would like to help on this.
I think the basic implementation is pretty straightforward:

1. Implement MaximizeToMinimize as subclass of QuadraticProgramConverter

The content for convert method is already given in:

https://github.com/Qiskit/qiskit-optimization/blob/23b63f6144e9a36efce7c0ab4646a527f28d0857/qiskit_optimization/algorithms/admm_optimizer.py#L389-L409

Since for every real function f we have:
argmax f(x) = - argmin (-f)(x)

There is nothing to do in method interpret. The solution vector x is the same. I would just check if they have the same number of variables. This is the same code as in 
https://github.com/Qiskit/qiskit-optimization/blob/23b63f6144e9a36efce7c0ab4646a527f28d0857/qiskit_optimization/converters/linear_equality_to_penalty.py#L166-L184

2. Add MaximizeToMinimize to QuadraticProgramToQubo conversion flow.
3. Make sure MaximizeToMinimize is in https://github.com/Qiskit/qiskit-optimization/blob/23b63f6144e9a36efce7c0ab4646a527f28d0857/qiskit_optimization/algorithms/optimization_algorithm.py#L353-L357

The question for me here is, whether we should do this always? As far as I know it should be okay to minimize in all algorithms. The function is currently used by grover and the (recursive-)minimum_eigen_optimizer.

4. Refactor all optimizers in algorithms package.


Greetings
Tom

**Comment by t-imamichi** [comment]
@tomtuamnuq Thank you for having an interest in this issue. Your understanding is correct.

As for 3, all algorithms should use `MaximizeToMinimize`. But, some don't have to use `_prepare_converters`, for example, ADMM applies converters manually because of the algorithm design. In this case we need to apply `MaximizeToMinimize` manually at https://github.com/Qiskit/qiskit-optimization/blob/54a6d0750492132aa019975e3a8648c507b7553c/qiskit_optimization/algorithms/admm_optimizer.py#L293

Feel free to start your implementation and ask me review.

**Comment by tomtuamnuq** [comment]
Hello @t-imamichi . Thank you for giving me the opportunity. I  would like to have your opinion on the changes of the results, as described in commit message. The method _interpret_samples, which was already moved to OptimizationAlgorithm, must still use https://github.com/Qiskit/qiskit-optimization/blob/92403b6f7c4e067602acc148411da1742fb356e6/qiskit_optimization/algorithms/optimization_algorithm.py#L469-L470

This accomplishes that OptimizationResult.samples has the right order(as the original maximization problem). The same goes for WarmStartQAOA samples.

I came across https://github.com/Qiskit/qiskit-optimization/blob/92403b6f7c4e067602acc148411da1742fb356e6/qiskit_optimization/algorithms/multistart_optimizer.py#L108-L115
The property can be set accidentally to a value smaller than 1. In this case multi_start_solve will fail. Shouldn't we prohibit this?

**Comment by t-imamichi** [comment]
@adekusar-drl What do you think of non-positive value for `_trial`? It results in no iteration at https://github.com/Qiskit/qiskit-optimization/blob/92403b6f7c4e067602acc148411da1742fb356e6/qiskit_optimization/algorithms/multistart_optimizer.py#L74
Should it be checked at the setter or can we leave it as is?

**Comment by adekusar-drl** [comment]
Agree, `_trials` should be more than 1 and such a check is a good idea!

Also, please, think of `num_trials` instead of `trials`, I guess we have a lot of places where we have `num_xxx` instead of plain `xxx`, but I'm not completely sure here as the renaming would break the interface.

**Comment by t-imamichi** [comment]
OK. I think it should be a separate PR. I will make an issue corresponding to `_trials`. As for naming, I don't think we need to change it now. Maybe we have a chance to revisit interface naming someday.

**Comment by adekusar-drl** [comment]
Sure it's up to you!
